### ISSUE TITLE
test issue 1 for epic A

### ISSUE THREAD

**Issue by joestubbs** [joestubbs/authenticator#2]
- [x] Subtask 1: Create design for sprockets
- [x] Subtask 2: Write sprockets class
- [ ] Subtask 3: Write tests for sprockets class
- [ ] Subtask 4: Update documentation on sprockets

**Comment by joestubbs** [comment]
another task list...
- [x] task 5
- [x] task 6

note that these tasks don't show up in the issue's "tasks" at the top.
